services:
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=alumno
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno
      - MYSQL_DATABASE=proyecto_laravel
    ports:
      - "23306:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8100:80"
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

volumes:
  db-data:
